# buildspec.yml
version: 0.2

phases:
  install:
    commands:
      - echo Installing NPM packages...
      - npm install
      # Script to detect changes and set build type
      - |
        if [ "$CODEBUILD_WEBHOOK_EVENT" = "PUSH" ]; then
          # For push events
          CHANGED_FILES=$(git diff --name-only $CODEBUILD_WEBHOOK_PREV_COMMIT $CODEBUILD_RESOLVED_SOURCE_VERSION)
        else
          # For other events or manual builds
          CHANGED_FILES=$(git ls-files)
        fi
        CONTENT_ONLY=true
        for file in $CHANGED_FILES; do
          if [[ ! $file =~ ^toucan/.*$ ]]; then
            CONTENT_ONLY=false
            break
          fi
        done
        export CONTENT_ONLY=$CONTENT_ONLY

  build:
    # TODO : for normal publishing of new episodes, we should not build the site, just run toucan.
    commands:
      - echo Build started on `date`
      - |
        if [ "${CONTENT_ONLY}" = "true" ]; then
          echo "Content-only changes detected, running minimal build..."
          npm run dist
        else
          echo "Source code changes detected, running full build..."
          npm run build
          npm run copy
          npm run dist # invokes Toucan
        fi

  post_build:
    commands:
      - echo "Build $CODEBUILD_BUILD_NUMBER completed on `date`, publishing to French Podcast will be done by the pipeline."

artifacts:
  files:
    - '**/*'
  name: adp-$(date +%Y%m%d%H%M%S).zip
  base-directory: 'dist'

# TODO conditional builds

    # preBuild:
    #   commands:
    #     - echo Installing NPM packages...
    #     - npm install
    #     - |
    #       if [ "$CODEBUILD_WEBHOOK_EVENT" = "PUSH" ]; then
    #         CHANGED_FILES=$(git diff --name-only $CODEBUILD_WEBHOOK_BASE_REF $CODEBUILD_RESOLVED_SOURCE_VERSION)
    #       else
    #         CHANGED_FILES=$(git diff --name-only HEAD^1 HEAD)
    #       fi
    #       CONTENT_ONLY=true
    #       for file in $CHANGED_FILES; do
    #         if [[ ! $file =~ ^toucan/content/.*\.md$ ]]; then
    #           CONTENT_ONLY=false
    #           break
    #         fi
    #       done
    #       echo "CONTENT_ONLY=$CONTENT_ONLY" >> $CODEBUILD_ENV_FILE
