[project]
name = "count-news"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "date-parser>=0.3",
    "feedparser>=6.0.12",
]
